server:
  port: 9411

spring:
  application:
     name: zipkin
     instance_id: zipkin_id
  rabbitmq:
    port: 5672
    host: rabbitmq
  datasource:
    schema: classpath:/mysql.sql    
    url: ${MYSQL_URI:jdbc:mysql://mysqlnode:3306/zipkin?autoReconnect=true} 
   # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: root
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql

logging:
  level:
    ROOT: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://mpOwner:mp19181975Secret@eureka:8761/eureka}
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
