version: "3.3"

services:
    
  rabbitmq:    
    image: rabbitmq
    env_file: env
    container_name: rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '1024mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    links:
     - zipkin
    volumes:
     - /opt/rabbitmq/logs/:/opt/rabbitmq/logs
    ports:
     - '15672:15672'
     - '5672:5672'
    networks:
     - socnet
    
  mongonode:
    env_file: env
    image: mongonode
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '4096mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    volumes:
      - /opt/mongodata/data:/data/db
      - /opt/mongodata/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      socnet:
        aliases:
          - mongonode
    
  mysql:
    env_file: env
    image: mysqlnode
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '4096mb'
        reservations:
          cpus: '0.1'
          memory: '250mb'   
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=zipkin
    volumes:
      - /opt/mysqldata/logs/:/opt/mysql/logs 
      - /opt/mysqldata/data:/var/lib/mysql    
    ports:
      - 3306:3306  
    networks:
     - socnet
     
       
  phpmyadmin:
   env_file: env    
   image: phpmyadmin/phpmyadmin
   deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '2048mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
   links:
    - mysql
   ports:
     - 9191:80
   environment:
     MYSQL_USERNAME: root
     MYSQL_ROOT_PASSWORD: root
     PMA_HOST: mysql
   networks:
     - socnet

  eureka:
    env_file: env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '1024mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    image: eureka  
    ports:
      - '8761:8761'
    volumes:
      - /opt/eureka/logs/:/opt/eureka/logs
    networks:
      - socnet

  zuul:
    image: zuul
    env_file: env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '2048mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    links:
      - eureka
    depends_on:     
      - eureka   
    volumes:
      - /opt/zuul/logs/:/opt/zuul/logs     
    ports:
      - '8079:8079'
    networks:
      - socnet
      
  zipkin:
    image: zipkin
    env_file: env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '2048mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    links:
      - eureka
      - mysql    
    depends_on:     
      - eureka      
      - mysql
    volumes:
      - /opt/zipkin/logs/:/opt/zipkin/logs     
    ports:
      - '9411:9411'
    networks:
      - socnet
  

  auth:
    image: auth
    env_file: env
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '1024mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongonode 
      - eureka
    depends_on:     
      - mongonode
      - eureka     
    ports:
      - '5001:5001'
    volumes:
      - /opt/auth/logs/:/opt/auth/logs
    networks:
      - socnet
      
  browser:
    image: browser
    env_file: env
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '1024mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    logging:
      options:
        max-size: "10m"
        max-file: "10"      
    links:     
      - eureka
    depends_on:      
      - eureka     
    ports:
      - '5002:5002'
    volumes:
      - /opt/browser/logs/:/opt/browser/logs
    networks:
      - socnet
            
  register:
    image: register
    env_file: env
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '1024mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    links:      
      - mongonode 
      - eureka
    depends_on:     
      - mongonode
      - eureka     
    ports:
      - '5003:5003'
    volumes:
      - /opt/register/logs/:/opt/register/logs
    networks:
      - socnet
      
      
  wiki:
    image: wiki
    env_file: env
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: '1024mb'
        reservations:
          cpus: '0.1'
          memory: '250mb' 
    links:      
      - mongonode 
      - eureka
    depends_on:     
      - mongonode
      - eureka     
    ports:
      - '5004:5004'
    volumes:
      - /opt/wiki/logs/:/opt/wiki/logs
    networks:
      - socnet 
   

networks:
  socnet:
    driver: overlay
