management:
  security:  
   enabled: false      
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
    
server:
    port: 5001
    
spring:
  application:
    name: auth
    
  data:
    mongodb:           
      uri: mongodb://BingoBongo:Abcdf@mongonode:27017/userDB?authSource=admin
     

jwt:
    header: Authorization
    expires_in: 300 
    mobile_expires_in: 400   
    secret: supersecret2019
