management:
  security:  
   enabled: false      
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
    
server:
    port: 5004
    
spring:
  application:
    name: wiki    
    
  cloud:
    discovery:
       service-id: wiki
       enabled: true
    inetutils:
       default-hostname: wiki
      
  zipkin:
    baseUrl: ${ZIPKIN_URI:http://zipkin:9411}
    enabled: true
  sleuth:
    enabled: true
    http:
      enabled: true   
    sampler:
    percentage: 1 
    
  data:
    mongodb:
      uri: ${MONGO_WIKI_URI:mongodb://BingoBongo:Abcdf@127.0.0.1:27017/wikiDB?authSource=admin} 
     

jwt:
    header: Authorization
    expires_in: 300 
    mobile_expires_in: 400   
    secret: supersecret2019
    zuulSecret: zuulSecret2025
    
eureka:
  instance:
    hostname: wiki  
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
  client:
    hostname: wiki   
    enabled: true
    registryFetchIntervalSeconds: 5   
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://mpOwner:mp19181975Secret@eureka:8761/eureka}
