version: '3'
services:  
  mongodb:
    build: .
    container_name: mongodbnode
    env_file: 
       - .env
    volumes:
      - mongodbvolume_data:/data/db
      - mongodbvolume_logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    command: mongod
    networks:
      marketplacenetwork:
        aliases:
          - mongodb
#    environment:
#      CRON_SCHEDULE: '0 1 * * *'
volumes:
  mongodbvolume_logs:
  mongodbvolume_data:
networks:
  marketplacenetwork:
